<SCL>
  <IED name="P1">
    <AccessPoint name="AP1">
      <Server>
        <LDevice inst="LD0">
          <LN0 lnClass="LLN0" inst="">
            <DataSet name="TripDS">
              <FCDA ldInst="LD0" lnClass="XCBR" doName="Pos" daName="stVal" />
            </DataSet>
            <GSEControl name="TripGOOSE" datSet="TripDS" appID="1001" />
          </LN0>
        </LDevice>
      </Server>
    </AccessPoint>
  </IED>
</SCL>
